apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-mysql-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: springboot.freundcloud.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springboot-mysql-service
                port:
                  number: 8080
  tls:
    - hosts:
        - springboot.freundcloud.com
      secretName: springboot-tls-secret

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-mysql-service
  labels:
    app: springboot
spec:
  type: LoadBalancer
  selector:
    app: springboot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: devacrfcaks.azurecr.io/springboot:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
