spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER_NAME}.mysql.database.azure.com:3306/${MYSQL_DATABASE}?useSSL=true&requireSSL=false
    username: ${MYSQL_USERNAME}@${MYSQL_SERVER_NAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true