spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:mysql://<your-azure-mysql-server-name>.mysql.database.azure.com:3306/<database-name>?useSSL=true&requireSSL=false
    username: <your-username>@<your-azure-mysql-server-name>
    password: <your-password>
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true