apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-core-deployment
  labels:
    app: aspnet-core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnet-core
  template:
    metadata:
      labels:
        app: aspnet-core
    spec:
      containers:
      - name: aspnet-core-container
        image: ${{ secrets.ACR_LOGIN_SERVER }}/aspnet-core-dotnet-core:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ["dotnet", "aspnet-core-dotnet-core.dll"]